name: regression
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - pip:
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     - optuna
  # for development only (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
